"""add previous_status to submissions

Revision ID: c929d32e2791
Revises: update_submission_statuses
Create Date: 2025-02-01 13:26:48.861311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c929d32e2791'
down_revision: Union[str, None] = 'update_submission_statuses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('previous_status', sa.Enum('PENDING', 'TEXT_APPROVED', 'PHOTO_PENDING', 'APPROVED', 'REVISION', 'COMPLETED', name='submissionstatus'), nullable=True))
    op.alter_column('submissions', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('submissions', 'revision_comment',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.alter_column('tasks', 'press_release_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'deadline',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tasks', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'is_admin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tasks', 'press_release_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.alter_column('submissions', 'revision_comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('submissions', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('submissions', 'previous_status')
    # ### end Alembic commands ###